name: Project Work 5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run files
      run: |
          chmod +x ./project/pipeline.sh
          ./project/pipeline.sh
      run: python ./project/Project_Work_4.py
      
