name: Exercise Feedback

on:
  push:
    branches:
      - main
    paths:
      - 'project/**'
  workflow_dispatch:

jobs:
  project-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: project # Specify the path to checkout as 'project'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Run pipeline
        run: |
          ls -la project # List files in the "project/" directory for debugging
          chmod +x project/pipeline.sh
          ./project/pipeline.sh
