name: Prject Feedback

on:
  push:
    branches:
    - main

jobs:
  project-feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ./project 

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Set up Python 3.11
      uses: actions/setup-python@v2 # Updated to version 2
      with:
        python-version: 3.11

    - name: Run pipeline
      run: ./project/pipeline.sh
