name: Project Feedback

on:
  push:
    branches:
      - main

jobs:
  project-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        path: main

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Project pipeline
      run: test.sh
      working-directory: project
