name: Project Feedback

on:
  push:
    branches:
      - main
    paths:
      - './project/**'
  workflow_dispatch:

jobs:
  project-feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: project # Specify the path to checkout as 'project'

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Set up Python 3.11
      uses: actions/setup-python@v2 # Updated to version 2
      with:
        python-version: 3.11

    - name: Run pipeline
      run: |
        cd project
        ls -la # List files in the current directory for debugging
        pwd # Print the current working directory for debugging
        chmod +x pipeline.sh
        ./pipeline.sh
