name: Project Feedback

on:
  push:
    branches:
    - main

jobs:
  project-ci:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'


    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Run project feedback
    - name: Project pipeline
      run: |
        cd https://github.com/Derin6/MADE_Project/tree/5022d139710e7d2349e24d818b4ec221ea14bd6e/project
        sh ./pipeline.sh
