name: Project Feedback

on:
  push:
    branches:
      - main

jobs:
  project-ci:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: https://github.com/Derin6/MADE_Project/tree/0a7f529fe156e718158a55502103f86a4187ed08/project

    steps:


    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Project pipeline
      run: sh pipeline.sh
