name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas
          pip install requests
          pip install sqlalchemy
          pip install example
          pip install openpyxl
          pip install --upgrade pandas openpyx
          pip install io
          pip install ssl

      - name: Run test.sh
        run: |
          chmod +x project/test.sh
          ./project/test.sh
