name: Project Feedback

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout exercise feedback
      uses: actions/checkout@v3
      with:
        repository: Derin6/MADE_Project/tree/main/project
        path: project

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Install dependencies

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Run exercise feedback
    - name: Project pipeline
      run: |
        ./project/pipleline.sh
