name: run Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to project directory
        run: cd project

      - name: Run pipeline.sh
        run: |
          chmod +x pipeline.sh
          ./pipeline.sh
